### ISSUE TITLE
Can you share the vgg-m weights file with me? I'd appreciate it if you would do that.

### ISSUE THREAD

**Issue by shining-love** [tzing/vgg-fms#2]
Can you share the vgg-m weights file with me? I'd appreciate it if you would do that.

**Comment by tzing** [comment]
I'm sorry that I do not work in this field for a while and I do not save the per-trained model.

**Comment by shining-love** [comment]
Thank you for your reply.I have got vgg-m weights from caffe model zoo.

2019-12-10 

yangjinyi_gis 



发件人：Tzu-ting <notifications@github.com>
发送时间：2019-12-08 01:40
主题：Re: [tzing/vgg-fms] Can you share the vgg-m weights file with me? I'd appreciate it if you would do that. (#2)
收件人："tzing/vgg-fms"<vgg-fms@noreply.github.com>
抄送："yang-gis"<yangjinyi_gis@163.com>,"Author"<author@noreply.github.com>

I'm sorry that I do not work in this field for a while and I do not save the per-trained model.
